name: Format and validate

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8
        with:
          terraform_version: ${{ vars.TF_VERSION_LATEST }}
          terraform_wrapper: false
      - run: terraform fmt -check -recursive
      - run: terraform init
      - run: terraform validate

  auth-check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
      - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8
        with:
          terraform_version: ${{ vars.TF_VERSION_LATEST }}
          terraform_wrapper: false
      - name: Terraform Init & Plan
        working-directory: examples/auth-check
        run: |
          terraform init
          terraform plan -var="network_name=ci-check-${{ github.run_id }}" -var="gcp_project_id=${{ vars.GCP_PROJECT_ID }}"
